API_KEY = 'D5SCBLKGFGCD2YRI'
ENDPOINT_SCHEMA_URL  = 'https://psrc-zgxgq7p.us-east1.gcp.confluent.cloud'
API_SECRET_KEY = 'cfltjYJeWQFELPodg5Iwx++Y1Ume/KNweJlc+eLWrseK7GatmIfZouP5+McItnDg'
BOOTSTRAP_SERVER = 'pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'UJYHRMVTRSLBQHM4'
SCHEMA_REGISTRY_API_SECRET = 'cfltDoqp22FIf6Mo/MaNNPkItN5PNLFMOx5X1Ntp/k4roW1L8QI60XYQwLAlTroA'


def config_values():
	return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
	