API_KEY = 'INSERT-TEXT'
ENDPOINT_SCHEMA_URL  = 'INSERT-TEXT'
API_SECRET_KEY = 'INSERT-TEXT'
BOOTSTRAP_SERVER = 'INSERT-TEXT'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'INSERT-TEXT'
SCHEMA_REGISTRY_API_SECRET = 'INSERT-TEXT'


def config_values():
	return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
	
